### ISSUE TITLE
duplicate role?

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#208]
I'm wondering if there's a conceptual difference between 
 * [R39](https://www.tbrc.org/xmldoc?rid=R39) ("Dalai Lama")
 * [R8LS12876](https://www.tbrc.org/xmldoc?rid=R8LS12876) ("Dalai Lama Tulku Line")

? If not, maybe one of them should be removed?

**Comment by karmagongde** [comment]
@eroux There is no much difference between R39 and R8LS12876. Would you please remove R39, since R8LS12876 is widely used in all the person record of Dalai Lamas. Thank you.

**Comment by eroux** [comment]
Thanks! a quick note: R39 is used in P197, maybe in a few others

**Comment by karmagongde** [comment]
Hi Elie,
We had more discussion on these 2 R#. if there is no issue of merge the data to the new website then please keep both R39 and R8LS12876. R39 is used for Dalai Lama's office and R8LS12876 is for Dalail Lama Tulku line. 
![screen shot 2018-09-17 at 10 23 26 am](https://user-images.githubusercontent.com/19337852/45630097-f6360a00-ba65-11e8-97cf-82268b4a3fc8.png)

**Comment by eroux** [comment]
Ok thanks

**Comment by xristy** [comment]
I'm reopening for two issues:

1) I think [P10519](https://www.tbrc.org/#!rid=P10519) should be withdrawn since it is a Person masquerading as [R8LS12876](https://www.tbrc.org/xmldoc?rid=R8LS12876)

2) since [P2305](https://www.tbrc.org/#!rid=P2305) occupied [R39](https://www.tbrc.org/xmldoc?rid=R39) for about 10 years after [P352](https://www.tbrc.org/#!rid=P352) was sent away but was not a member of [R8LS12876](https://www.tbrc.org/xmldoc?rid=R8LS12876), is this the only reason to distinguish [R39](https://www.tbrc.org/xmldoc?rid=R39) and [R8LS12876](https://www.tbrc.org/xmldoc?rid=R8LS12876)? I can not find any other references to these two offices/roles in the data other than the 14 Dalai Lamas and [P2305](https://www.tbrc.org/#!rid=P2305).

**Comment by xristy** [comment]
@karmagongde also is it plausible that [P2305](https://www.tbrc.org/#!rid=P2305) could have been an occupant of the [office of regent](https://www.tbrc.org/xmldoc?rid=R36) rather than [R39](https://www.tbrc.org/xmldoc?rid=R39)?
