### ISSUE TITLE
PDF of only 40 pages for open access works

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#265]
going to https://www.tbrc.org/#!rid=W3CN515 when not logged, I see that I can only access the first 20 and last 20 pages even though the work is in open access. I can actually see all the images in the image viewer, but when I download "full PDF", I'm getting only 40 pages. @xristy wdyt?

**Comment by xristy** [comment]
For an ```OPEN_ACCESS``` work  if the user is in group _TBRC_ or _FULL_ then the user gets ```OpenAccess```; otherwise, if the user is not in one of the two groups or not logged in at all then ```SampleAccess``` is returned from ```Queries.accessRight```:
```java
    case OPEN_ACCESS:
        if (session.getAttribute(FULL) != null) {
            return AccessRight.OpenAccess;
        } else if (session.getAttribute(USER) != null) {
            return AccessRight.Sample;
        } else {
            return AccessRight.Sample;
        }
```
Then in ```ImageService.doGet``` the relevant check is:
```java
    if ((limitGuest && right.equals(AccessRight.Sample)) || right.equals(AccessRight.FairUse)) {
        if (pageNum < firstNum + pageLimit || pageNum > lastNum - pageLimit) {
            // valid sample page
        } else {

            // send back an image indicating only sample access allowed
            . . .
        }
    }
```
**but** the server is currently configured so that ```limitGuest == false``` thus allowing all images to be viewed.

However, in ```PdfServerImpl.genDownload``` there is no dependence on the ```limitGuest``` configuration item so that:
```java
    switch (right) {
    case All:
    case OpenAccess:
    case CTC:
        return genPdf(right, work, volume, startPage, endPage, pageLimitDefault, "any");
    case Sample:
    case FairUse:
        return genPdf(right, work, volume, startPage, endPage, pageLimit, "abs");
    default:
        log("genDownload NO ACCESS for " + right + " to work: " + work + "[" + volume + "] pp." + startPage + "-" + endPage + " from " + remoteAddr());
        return failResponse(right, work, volume, startPage, endPage);
```
and ```Sample``` will only generate the first and last 20 pages.

The other relevant configuration item is ```groupFull``` which if ```true``` assigns new users to group _FULL_ and otherwise to no group. Currently the configuration has ```groupFull == false```

This state of affairs goes back to late Jan 2019 when there was the _attack_ creating bot users (all in group _FULL_) and launching large numbers of ```genDownload``` requests. The current configuration essentially requires new users that want _FULL_ access to contact info@tbrc.org and be added to the group.

**Comment by eroux** [comment]
I see... do you think we still need that?

**Comment by xristy** [comment]
I have checked with Travis to see how frequently they are fielding requests for full access and he says they get 1 or 2 a week. Travis says it's no big deal for them to handle that amount of requests.

We could change the configuration so that ```groupFull == true``` (only a server bounce is needed). Then new users would not be contacting the staff for full access.

We have always required users to actually be logged in for full pdf downloads. The changes from last year permit non-logged in users to view all images

If another bot attack is launched then we can revert the configuration.
