### ISSUE TITLE
tbrcHoldings field

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#275]
Hi Karma,

I'm investigating the migration of the `tbrcHoldings` field in BUDA. I notice that there are a few different patterns:
- just "1", by far the most common with 21,000 occurences (ex: W27022), what does this mean?
- sometimes a bit more like "2" (ex: W18126) or "4" (ex: W20476)
- sometimes it's clear that we own a real copy, indicated by "tbrc holds inkprint copy" (ex: W00EGS1017093, W24989, W19306), or at least that we used to
- sometimes it just says that we have scans (which I suspect is self-obvious and not very helpful), indicated with "TBRC holds digitally color scanned images, tiffs and pdf files" (W3CN1475, W3CN1598)
- sometimes it has a "tbrc volume number" indication like in "tbrc holds digitally scanned images, tiffs and pdf files,\ntbrc volume number 0444" (ex: W19604, W23417), what is that?
- sometimes it just has a number at the end, which I suspect represents the tbrc volume number? like in "tbrc holds digitally scanned images, tiffs and pdf files\n2655" (ex: W23773)

My guess is that the volume number are for the things that went into the Gene Smith Library in China? So I suspect it's not very helpful to spend time isolating the volume number... Also, what is the current cataloging practice for this field?

Thanks!

**Comment by karmagongde** [comment]
Hi Elie,
Those different patterns in "TBRC Holdings" are changed according to the authority's suggestion in the different time periods. 

- In the field "TBRC Holdings" 1 or 2 or 4 etc. are the physical books holds by the TBRC. Around 95% of inkprint books and Pecha are already given to Gene Smith Library in China and GEBIS. Now, the TBRC holdings the "inkprint copy" field became irrelevant. In those work numbers (ex: W27022) the TBRC holdings note are on the field "note". 
- Since the digitized images are in color, therefore, added color. 
- "tbrc volume number" tbrc volume number 0444" (ex: W19604, W23417); "tbrc holds digitally scanned images, tiffs and pdf files\n2655" (ex: W23773) are the image group number. I believe these volume numbers are generated manually when there was no scan-request function. This is image group number.
- The volume number is general information of physical copies holds by TBRC. This number does not have any connection with the books/pecha sent to the Gene Smith Library in China.
- Currently, the librarian adds "tbrc holds digitally scanned images, tiffs and pdf files" in TBRC holdings field.

Best,

**Comment by eroux** [comment]
Excellent, that's really helpful thanks! Do we have a list of what's been given to the library in China and to GEBIS?

**Comment by karmagongde** [comment]
We do not have any single list of books given to GEBIS. 
As well as I don't have every list of books given to the SouthWest University of China. At that time I was not a manager to organize that project.

**Comment by eroux** [comment]
ok, thanks!
