### ISSUE TITLE
out of order volumes in W4CZ7445

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#299]
currently we have:

vol 30 = I1KG9897 = khri rgyad ka
vol 31 = I1KG9898 = khri rgyad kha
vol 32 = I1KG9899 = khri rgyad ga / khri pa ga
vol 33 = I1KG9900 = khri pa nga
vol 34 = I1KG9901 = shes rab sna tshogs kA
vol 35 = I1KG9902 = nyi khri ka
vol 36 = I1KG9903 = nyi khri kha
vol 37 = I1KG9904 = nyi khri ga
vol 38 = I1KG9905 = nyi khri nga
vol 39 = I1KG9906 = brgyad stong ka

but according to Adarsha's and rKTs' outline it should be:

vol 30 = I1KG9902
vol 31 = I1KG9903
vol 32 = I1KG9904
vol 33 = I1KG9905
vol 34 = I1KG9897
vol 35 = I1KG9898
vol 36 = I1KG9899
vol 37 = I1KG9900
vol 38 = I1KG9906
vol 39 = I1KG9901

@karmagongde can we fix the order the volumes in the work record? I think it's ok to do that without making new scan requests, requiring sync of images, etc. What do you think?

**Comment by karmagongde** [comment]
I will reorder these volumes according to them. So, both the outline and images folders on the Archive will be the same. This won't need to create a new scan-request but have to Re-sync these 10 volumes.

**Comment by eroux** [comment]
Ok thanks! I'm not sure what you mean by "both the outline and images folders on the Archive will be the same"?

**Comment by karmagongde** [comment]
The order of the Image Group will be in the right order in both.

**Comment by eroux** [comment]
ok, I understand the appeal of having the alphabetical order of the image group IDs corresponding to the order of volumes, but it's really inconvenient to move images from one image group id to another:
- it takes more time on your side and on AO's side too
- moving forward it's really best if images and volume URLs don't change, so that our partners can use them directly

If you rename all the images, this means that people who were using the IIIF endpoint will need to also change all the images on their side, that's what we'll have to do for rKTs if we resync everything... so, would it be possible not to resync everything and just assign different volume numbers to the image groups?

**Comment by TBRC-Travis** [comment]
> would it be possible not to resync everything and just assign different volume numbers to the image groups?

yes, I agree.  if we can leave the same image group IDs but just change the volume numbers that would be ideal.

**Comment by karmagongde** [comment]
Only to display on the website simply changing the volume numbers would be fine. I think when we distribute for CTC, DLD, Lineage Drive the order of the volume won't match which is on the outline unless these are changed on Archive.

**Comment by eroux** [comment]
hmm, that's an interesting point... @xristy do you know if there might be a way to fix this? Maybe prefixing the image group id by the volume number in the folder name ?

**Comment by xristy** [comment]
I'm sorry. I actually don't understand the problem. I see that what was volume 30 will now be volume 34, and so on. But I'm not sure where the outline for the CTC, DLD, and Lineage Drives is being generated. I don't know how putting the volume num in front of the imagegroup folder name will help other than gyrating a bunch of s/w.

**Comment by eroux** [comment]
hmm I don't either... well... in any case, I'm importing the outline from rKTs into BUDA so it won't be on tbrc.org anyways

**Comment by TBRC-Travis** [comment]
I'm not knowledgeable about how this will affect outlines but in terms of prepending the volume number to the image group id, this would be helpful for ordering things correctly when physical media is involved.  In the past I believe @karmagongde has requested that I move the images around so that they match the corresponding new image group number, which requires all the images to be renamed and re-synced.  Elie and I are trying to find a solution where we don't have to modify the underlying assets but some sort of pointer at a higher level where the volumes can be adjusted accordingly but we don't need to do a big re-shuffle of images, which is a cumbersome process.

**Comment by xristy** [comment]
so the correction is just in BUDA and there are no CTC, DLD, or Lineage Drive issues it seem

**Comment by TBRC-Travis** [comment]
@xristy I'm not knowledgeable about how this will affect outlines but in terms of prepending the volume number to the image group id, this would be helpful for ordering things correctly when physical media is involved.  In the past I believe @karmagongde has requested that I move the images around so that they match the corresponding new image group number, which requires all the images to be renamed and re-synced.  Elie and I are trying to find a solution where we don't have to modify the underlying assets but some sort of pointer at a higher level where the volumes can be adjusted accordingly but we don't need to do a big re-shuffle of images, which is a cumbersome process.

**Comment by TBRC-Travis** [comment]
whoops.  @xristy I accidentally deleted your comment rather than my own.  sorry!

**Comment by xristy** [comment]
so the correction is just in BUDA and there are no CTC, DLD, or Lineage Drive issues it seems

**Comment by eroux** [comment]
@karmagongde the volumes of W3CN20612 are also in an unusual order... Inside sections the volumes are ok, but the sections are unusual:
- vol 1-12: bum 
- vol 13-15: nyi khri
- vol 16: brgyas stong
- vol 17-22: dkon brtsegs
- vol 23-26: phal chen
- vol 27-30: khri brgyad / khri pa
- vol 31-62: mdo sde
- vol 63-75: 'dul ba
- vol 76: shes rab sna tshogs
- vol 77-96: rgyud 'bum
- vol 97-98: gzungs 'dus
- vol 99: dri med 'od
- vol 100: dkar chag
- vol 101-102: rnying rgyud

Usually the Derge editions are:
- 'dul ba
- 'bum
- nyi khri
- khri brgyad / khri pa
- brgyad stong
- shes rab sna tshogs
- phal chen
- dkon brtsegs
- mdo sde
- rgyud 'bum
- rnying rgyud
- dri med 'od
- dkar chag

I don't mind leaving the volumes in that order if that's how we found them, I just want to make sure that we won't reorder them later as this would induce more manual work in the future... what do you think?

**Comment by eroux** [comment]
(my preference would be to reorder them now)

**Comment by karmagongde** [comment]
Generally, all the Kangyur, Tengyur, and multi volumes sets should be arranged according to their volume order listed on Karchag. If the Karchag is missing, we have to compare the contents with similar works and arrange the order of the volumes. 

The reviewed the Karchag of W3CN20612 and it is the same as other Derge Kangyur. So I will arrange the volume order of W3CN20612 as other Derge Kangyur.

When volume arranging is done, I will let you all Know.

**Comment by eroux** [comment]
ok great! Well, if we order volumes according to the karchag, then I think W1PD96684 is also out of order as vol 61 (I1PD106713) should be volume 1 according to the karchag if I understand correctly... I'm not sure what the overall order should be though, according to the rKTs outline, vol 61 should be "mdo sna tshogs, i", but I couldn't locate it.

**Comment by karmagongde** [comment]
@TBRC-Travis @eroux 
Hi Travis,
I have uploaded the 10 volumes of W4CZ7445 to replacement and a full set of Kangyur W3CN20612 in ReadyToProcess/Replacement. 
For the 10 volume partial replacement, I did the renaming and it is ready to sync. I checked the web images and Archive images of W4CZ7445 and both look like the same size. Please double-check and if it is the same size, please replace the Archive images too.
Regarding the W3CN20612, I have rearranged them in the right order with numbered on the volumes. Please rename them with correct IG numbers. I removed all the incorrect scan request 2 Biblio pages. Please download IG folders from Scan Request Directory. 

If you have any questions please let me know.
Best, Karma

**Comment by TBRC-Travis** [comment]
Excellent.  Thanks @karmagongde.  I'll work on this later today or tomorrow.

**Comment by eroux** [comment]
@karmagongde I'd like to raise the topic during today's meeting as this will lead to a lot of additional work on my side (to fix all the files in https://github.com/brunogml/rKTs/tree/master/paginations/3CN20612 that give the correspondence between page number and image file)... If there's a real use case not to do so I'm ok to do it, but I'm still not sure what you're referring to. Can you please elaborate? This might be something we can fix on a technical level if we identify the problem clearly.

**Comment by TBRC-Travis** [comment]
@eroux perhaps the three of us can have a meeting specifically about this?  I'm not sure the staff meeting is the right venue to have this kind of detailed discussion.

**Comment by eroux** [comment]
sure, why not. Maybe we could involve Jim too? What would be a good time for such a meeting?

**Comment by TBRC-Travis** [comment]
Sure.  Tomorrow looks pretty open.  11am EST?

**Comment by eroux** [comment]
ok yes, that would work for me

**Comment by karmagongde** [comment]
@eroux I created a volume order spreadsheet for W3CN20612. I hope this will help to reorder the GitHub volume order so you don't have to fix any paginations. 
[W3CN20612-volume-order.xlsx](https://github.com/buda-base/library-issues/files/5378818/W3CN20612-volume-order.xlsx)

**Comment by karmagongde** [comment]
Since volume order rearranged according to the Derge Karchag the two Biblio pages generated at the scan request it shows volume 1 of 103, volume 2 of 103 etc. So it needs to change as volume orders. Travis will add the correct two scan request biblio pages during the renaming. Therefore the pagination in GitHub will remain the same counts.

Image Group number OR image numbers are often irregular? Please show me an example. I will look and explain. If those are errors, we have to fix them.

**Comment by eroux** [comment]
image names are often irregular, for instance:
- sometimes a number is missing (sometimes it indicates a missing page, sometimes not), for instance in [I1KG9128](http://iiifpres.bdrc.io/il/v:bdr:I1KG9128) there's no file `I1KG91280003.jpg` but it doesn't indicate a missing page
- sometimes there are funny names, like `I1GS660450502a.tif` in [I1GS66045](http://iiifpres.bdrc.io/il/v:bdr:I1GS66045)
and we've spent a considerable energy spotting all these irregularities, all the pagination errors in the original, the duplicate scans, the missing images, etc. this is a humongous work that there's no way we're going to do again for no reason.

But to address your main point: the volume number (ex: `3`) is totally independent of the image group identifier (ex: `I3CN20678`). The system does not assume that the alphabetical order of image group identifiers (ex: `I3CN20678` < `I3CN20679`) holds any kind of significance. So assigning different volume numbers to image groups will make our system reorder them, without having to resync all the images. I can clarify if anything is not clear but this is really fundamental.

**Comment by JannTibetan** [comment]
When we work with partners to share data we want the work to be simple and practical. Another concern is to provide our partners with persistent, unchanging URLs. If BDRC changes our IIIF endpoints often then other organizations will be leery of using our images and metadata. For these reasons I would like the resolution to this issue to not involve renaming and resending images. We can make the needed changes to the website without altering the archive; this is a metadata issue. 
I understand that there are still unresolved issues regarding the CTC and DLD but they will have to be resolved in some other way. For now let's just worry about the website and our IIIF links.   Thanks!

**Comment by xristy** [comment]
Regarding the ordering of volumes in [`W3CN20612`](https://www.tbrc.org/#!rid=W3CN20612) and [`W4CZ7445`](https://www.tbrc.org/#!rid=W4CZ7445) the appropriate solution is to simply reorder the imagegroups in the volume maps of the two work records.

Why? 
- There are **no** Outlines on tbrc.org (or currently on BUDA) that will need to be corrected.
- [`W3CN20612`](https://www.tbrc.org/#!rid=W3CN20612) occurs in CTC-16 but the outline on  the CTC-16 disk will still refer to volume ordering as what when the master disk was made.
- moving images between imagegroups will wreck any URLs people may have captured to imagegroups from tbrc.org since the urls refer to imagegroup rids, vol #, start, end pp. So swapping a bunch of images from `I1KG9897` to `I1KG9902`, for example, will render such URLs useless. As it stands the imagegroup rid and the pp will still be valid. I doubt there are many such instances in any event to justify anymore work than reordering the volume maps

This will satisfy @JannTibetan's intent above.

**Comment by eroux** [comment]
I've updated the volume maps of W1PD96684, W3CN20612 and W4CZ7445, I'm going to update the rKTs outlines and reimport them. @karmagongde can you double check? I'll close the issue tomorrow if there's no further problem

**Comment by karmagongde** [comment]
@eroux Thanks for updating volume maps. Now the volume orders are displayed fine on the Website as listed on Karchag. Please note: in **W1PD96684** the volume no. 62 (ཨི་དུམ་པ། འཕགས་པ་བསྐལ་པ་བཟང་པོ་པ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།) is missing in Peking Kangyur from Dr. Raghu Vira and Dr. Lokesh Chandra collection.

**Comment by eroux** [comment]
Yes, this is a strange feature of tbrc.org which doesn't display the volume number of the metadata... it should be fixed on BUDA (after tomorrow's migration that will have the changes I made)
