### ISSUE TITLE
Bardan Mss RID 

### ISSUE THREAD

**Issue by brunogml** [buda-base/library-issues#302]
I noticed that BDRC ascribes 7 Work RID to the Bardan Collection (https://www.tbrc.org/#library_BannerSearchResults-&quot;bardan&quot;), but all these manuscripts belong to the same collection, and the pagination goes uninterrupted through 5 of them. Can you ocheck please. Thanks.

**Comment by eroux** [comment]
The URL of the search doesn't work but the RIDs are:
- W8LS15931 / I8LS15936
- W8LS15932 / I8LS15938
- W8LS15939 / I8LS15941
- W8LS15942 / I8LS15944
- W8LS15946 / I8LS15950
- W8LS15945 / I8LS15948
- W8LS15951 / I8LS15953

@brunogml can you indicate the correct order of these?

**Comment by eroux** [comment]
@karmagongde I can't find the images for W8LS15931 / I8LS15936, do you know where they might be on rs5? Also, it seems volume zha is missing, do you know if we have the images somewhere?

**Comment by karmagongde** [comment]
@eroux  The image of W8LS15931-I8LS15936 is located at Incoming/scans/ReadyToProcess/Mangaram/ReceivedFromMangaram/W8LS15931. 
If volume Zha does not have work numbers means it is missing. We do not have another place to look for volume Zha. All the images from the University of Vienna are cataloged and images should be in ReadyToProcess.

**Comment by eroux** [comment]
Thanks! Found it. I think volume zha is after volume wa in W8LS15945

**Comment by eroux** [comment]
So I guess this leaves the following question: @karmagongde is there a reason why these volumes are split in different works? If not can we just move all the image groups to one of the works? (ccing @TBRC-Travis as this will require some movements in the archive too)

**Comment by karmagongde** [comment]
The librarian LS has cataloged individual. Many times it is dependent on how the folder received with sub-folders or instruction. 

We can group under one work number. Please refresh the work numbers and the volume order to make them in one group.

Actually, volume zha is with volume wa in W8LS15945, see image number 47. Looks like both of them are incomplete volume.

**Comment by eroux** [comment]
Ok thanks!

Let's make one work, it can be a new one or else let's use W8LS15931, it could be named `bka' 'gyur (bardan)` (@brunogml what's the proper Tibetan for Bardan?), and there could be a note saying that not everything has been photographed. 

For the imagegroups, we could do the following so that it matches the [catalog of rKTs](https://github.com/brunogml/rKTs/blob/master/zzz%20in%20progress/Kanjur/bardan.xml): 

- I8LS15936 (mtshan rgyud ka)
- I8LS15938 (de shying ka)
- I8LS15941 (dkaug ta)
- I8LS15944 (snying rje ma)
- I8LS15948 but taking only img 1 to 46 (wa)
- new volume taking img 47 to end of I8LS15948 (zha)
- I8LS15950 (blo gros tha)

but the problem is that:
- I8LS15953 (ka)

doesn't fit in the catalog... @brunogml are these images that should be in another volume? or maybe there's a volume missing in the catalog?

**Comment by brunogml** [comment]
bardan is 'bar gdan dkon pa

**Comment by brunogml** [comment]
![IMG_20201022_193202.jpg](https://user-images.githubusercontent.com/29774037/96908770-6319fa80-149d-11eb-81ea-63483855384d.jpg)

**Comment by karmagongde** [comment]
I modified the catalog record W8LS15931 for bka' 'gyur/ ('bar gdan dgon pa/).

When I get confirmation of the numbers of volumes in this set I will generate the scan-request. @brunogml Please let me know the exact volume numbers and any notes to add. Thanks, Borno for the info image.

**Comment by eroux** [comment]
@karmagongde the mystery is now partially solved, so in the new work there should be, in that order:
- I8LS15936
- I8LS15938
- I8LS15941
- I8LS15944
- I8LS15948 but taking only img 1 to 46
- new volume taking img 47 to the end of I8LS15948
- I8LS15950
- a new volume containing the images in `/Incoming/scans/Inbox/Bruno/Bardan/8 gser 'od`
- a new volume containing the images in `/Incoming/scans/Inbox/Bruno/Bardan/MNS`

would that work? Thanks!

**Comment by karmagongde** [comment]
@eroux Ok, I will generate 9 volumes for W8LS15931, bka' 'gyur/ ('bar gdan dgon pa/).
Thanks.

**Comment by eroux** [comment]
excellent, thanks!

**Comment by brunogml** [comment]
I would rater call it mdo mang than bka' 'gyur

**Comment by karmagongde** [comment]
@brunogml Thanks Bruno. Title Kagyur is too broad. I changed the title of W8LS15931, please check. 
Also, please add a note for Scanned by: 
So, I can add when I generate the scan-request.

'bar gdan dgon par bzhugs pa'i rgyud dang mdo sde sogs pod khag cig/
'bar gdan dgon pa gsang sngags chos gling du bzhugs pa'i rgyud dang mdo sde sogs kyi pod khag cig/

**Comment by eroux** [comment]
the scaninfo for all the Viennese works is `Digitization by the Cultural History of the Western Himalaya-Project "Tibetan Manuscripts" (University of Vienna)`, @brunogml if it works for you maybe we can keep this one?

**Comment by brunogml** [comment]
We changed "University of Vienna Cultural History of the Western Himalaya Project" into "University of Vienna - Tibetan Manuscript Project Vienna (TMPV)".

**Comment by eroux** [comment]
@karmagongde sorry for this last minute change, but the two images that are in the `/Incoming/scans/Inbox/Bruno/Bardan/MNS` folder are actually color versions of two images that are in `/Incoming/scans/ReadyToProcess/Mangaram/ReceivedFromMangaram/W8LS15931/images/W8LS15931-I8LS15936` (`I8LS159360009.jpg` and `I8LS159360010.jpg`), so they can be moved in I8LS15936 instead of going in a separate one... sorry!

**Comment by karmagongde** [comment]
@TBRC-Travis Could you please help to copy all the web images and archive images of the following work numbers from Archive and move them at Incoming/scans/Inbox/Bruno. These all are combining into W8LS15931 and making 9 volumes set. I will arrange them in the volume order. 

W8LS15932 / I8LS15938
W8LS15939 / I8LS15941
W8LS15942 / I8LS15944
W8LS15946 / I8LS15950
W8LS15945 / I8LS15948
W8LS15951 / I8LS15953

**Comment by TBRC-Travis** [comment]
@karmagongde I've copied all of these works here for you:  `Inbox/Bruno/Bardan/CopiedFromArchive`

**Comment by karmagongde** [comment]
@TBRC-Travis Hi Travis, I have arranged all the volumes with subfolders. Volume no. 1. does not have the Archive and Source folders. Rest has all the folder, Archive, Images, and Source.

These need to rename. Every images folder has the JSON file and I kept as it is.

The images are located at: incoming/scans/ReadyToProcess/Replacement/W8LS15931.

After syncing this work number W8LS15931, Please remove the following folders from Archive.
W8LS15932 / I8LS15938
W8LS15939 / I8LS15941
W8LS15942 / I8LS15944
W8LS15946 / I8LS15950
W8LS15945 / I8LS15948
W8LS15951 / I8LS15953 Since these are combined in W8LS15931. I will withdraw these catalog records.

**Comment by TBRC-Travis** [comment]
@karmagongde sounds good.  I'll work on this tomorrow.

**Comment by TBRC-Travis** [comment]
@karmagongde W8LS15931 is now synced and online:  https://library.bdrc.io/show/bdr:W8LS15931

Please review the images and let me know if they look good.  Once you've verified the images I will delete the old work numbers.

**Comment by eroux** [comment]
thanks a lot!

**Comment by eroux** [comment]
@karmagongde also if the images look good to you, can you withdraw the other records?

**Comment by karmagongde** [comment]
@TBRC-Travis @eroux Hi Travis, I checked the images in W8LS15931 and looks fine. Also, I have withdrawn the following work numbers in favor of W8LS15931. So, please remove all the folders from Archive. Thank you.
W8LS15932
W8LS15939
W8LS15942
W8LS15945
W8LS15946
W8LS15951

**Comment by TBRC-Travis** [comment]
@karmagongde I've removed the images for these withdrawn work numbers:

W8LS15932
W8LS15939
W8LS15942
W8LS15945
W8LS15946
W8LS15951
