### ISSUE TITLE
Discrepancies in the FPL/EAP list

### ISSUE THREAD

**Issue by eroux** [buda-base/library-issues#311]
I recently got my hands on the EAP 1150 catalog and I compared the list of images to the ones that is indicated in https://github.com/buda-base/library-issues/issues/242 .

Here are the differences

works in the EAP catalog but not in the original EAP list:
- 10042: W1EAP10042 has images, W1FPL10042 too but is on hold
- 6223: W1EAP6223 has images, W1FPL6223 doesn't but it's released

works in the original EAP list but not in the EAP catalog:
- 7030: W1EAP7030 has no image and is withdrawn, W1FPL7030 has no image and is released
- 6078: W1EAP6078 has no image and is withdrawn ("in favor of W1EAP6223" says the log message), W1FPL6078 has no image and is onHold

so there seems to have been some changes from the initial list of EAP works, and it seems some cleanup could be done, such as:
- withdrawing W1FPL6223 in favor of W1EAP6223 (or maybe changing its status to onHold?)
- setting W1FPL6078 status to released

Are there other changes that I might have missed? CCing @TBRC-Travis @TBRC-pmench  @xristy

**Comment by TBRC-Travis** [comment]
> 10042: W1EAP10042 has images, W1FPL10042 too but is on hold

As part of the EAP project we decided not to withdraw the equivalent FPL records but it does look like we decided to mark them as "onHold".

> 6223: W1EAP6223 has images, W1FPL6223 doesn't but it's released

When we created the initial FPL catalog records years ago all the works were initialized as "released".  In this case, I think we simply forgot to mark W1FPL6223 as "onHold".  W1FPL6223 hasn't been scanned yet which is why there are no images.

**Comment by TBRC-Travis** [comment]
> 7030: W1EAP7030 has no image and is withdrawn, W1FPL7030 has no image and is released

While attempting to scan W1EAP7030 they discovered that the manuscript was damaged.  We chose another manuscript in its place (W1EAP10042).  W1FPL7030 has no images because it has not been scanned yet as part of the ongoing FPL project.  As mentioned in my previous comment, all FPL records were initialized as "released" when the records were created even though they had not been scanned yet.

> 6078:  has no image and is withdrawn ("in favor of W1EAP6223" says the log message), W1FPL6078 has no image and is onHold

As described W1EAP6078 was replaced by W1EAP6223.  W1FPL6078 has not yet been scanned, but since it no longer has an equivalent EAP record it should be marked as "released" to match all of our other non-EAP FPL records.

**Comment by TBRC-Travis** [comment]
> withdrawing W1FPL6223 in favor of W1EAP6223 (or maybe changing its status to onHold?)

yes, please update the status of W1FPL6223 to "onHold"

> setting W1FPL6078 status to released

yes, please update the status of W1FPL6078 to "released"

**Comment by TBRC-pmench** [comment]
6078 was also too damaged to scan. It was replaced by 6223.

**Comment by eroux** [comment]
ok, thanks everyone! @xristy could you update the following:

- changing the status of W1FPL6223 to onHold
- changing the status of W1FPL6078 to released

**Comment by xristy** [comment]
Done

**Comment by eroux** [comment]
excellent, thanks!
